version: '3.8'
services:
    php:
        image: yiisoftware/yii2-php:8.2-apache
        volumes:
            - ~/.composer-docker/cache:/root/.composer/cache:delegated
            - ./:/app:delegated
        ports:
            - '8080:80'
    database:
        image: mysql:8.1
        restart: always
        environment:
            MYSQL_DATABASE: 'ahrfact'
            MYSQL_ROOT_PASSWORD: 'tiger'
        ports:
            - '3307:3306'
        volumes:
            - ./database/data/mysql:/var/lib/mysql
volumes:
    mysql: {}