<?php

return [
    'adminEmail'  => 'admin@example.com',
    'senderEmail' => 'noreply@example.com',
    'senderName'  => 'Example.com mailer',
    'states' => [
        "Aguascalientes"      => "Aguascalientes",
        "Baja California"     => "Baja California",
        "Baja California Sur" => "Baja California Sur",
        "Campeche"            => "Campeche",
        "Chiapas"             => "Chiapas",
        "Chihuahua"           => "Chihuahua",
        "Coahuila"            => "Coahuila",
        "Colima"              => "Colima",
        "Ciudad de México"    => "Ciudad de México",
        "Durango"             => "Durango",
        "Guanajuato"          => "Guanajuato",
        "Guerrero"            => "Guerrero",
        "Hidalgo"             => "Hidalgo",
        "Jalisco"             => "Jalisco",
        "Estado de México"    => "Estado de México",
        "Michoacán"           => "Michoacán",
        "Morelos"             => "Morelos",
        "Nayarit"             => "Nayarit",
        "Nuevo León"          => "Nuevo León",
        "Oaxaca"              => "Oaxaca",
        "Puebla"              => "Puebla",
        "Querétaro "          => "Querétaro ",
        "Quintana Roo"        => "Quintana Roo",
        "San Luis Potosí"     => "San Luis Potosí",
        "Sinaloa"             => "Sinaloa",
        "Sonora"              => "Sonora",
        "Tabasco"             => "Tabasco",
        "Tamaulipas"          => "Tamaulipas",
        "Tlaxcala"            => "Tlaxcala",
        "Veracruz"            => "Veracruz",
        "Yucatán"             => "Yucatán",
        "Zacatecas"           => "Zacatecas"
    ],
    'regimen_fiscal' => [
        "605" => "605 - Sueldos y Salarios e Ingresos Asimilados a Salarios",
        "606" => "606 - Arrendamiento",
        "608" => "608 - Demás ingresos",
        "610" => "610 - Residentes en el Extranjero sin Establecimiento Permanente en México",
        "611" => "611 - Ingresos por Dividendos (socios y accionistas)",
        "612" => "612 - Personas Físicas con Actividades Empresariales y Profesionales",
        "614" => "614 - Ingresos por intereses",
        "615" => "615 - Régimen de los ingresos por obtención de premios",
        "616" => "616 - Sin obligaciones fiscales",
        "621" => "621 - Incorporación Fiscal",
        "622" => "622 - Actividades Agrícolas, Ganaderas, Silvícolas y Pesqueras",
        "629" => "629 - De los Regímenes Fiscales Preferentes y de las Empresas Multinacionales",
        "630" => "630 - Enajenación de acciones en bolsa de valores",
        "625" => "625 - Régimen de las Actividades Empresariales con ingresos a través de Plataformas Tecnológicas",
        "626" => "626 - Régimen Simplificado de Confianza",
    ],
];
